version: 2.1
jobs:
  build:
    macos:
      xcode: "14.3.1"
    environment:
      GOROOT: /usr/local/go
      PATH: $PATH:$GOROOT/bin:$HOME/go/bin
    steps:
      - run:
          name: Install Git
          command: |
            brew install git
            git --version
      - run:
          name: Checkout
          command: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
      - run:
          name: Install Go
          command: |
            uname -a
            # For amd64
            curl -fLO https://go.dev/dl/go1.20.6.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.20.6.linux-amd64.tar.gz
            echo 'export PATH=/usr/local/go/bin:"$HOME"/go/bin:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            echo $PATH
            
            # For arm
            # curl -fLO https://go.dev/dl/go1.20.6.darwin-arm64.tar.gz
            # sudo rm -rf /usr/local/go
            # sudo tar -C /usr/local -xzf go1.20.6.darwin-arm64.tar.gz
            # echo 'export PATH=/usr/local/go/bin:"$HOME"/go/bin:"$PATH"' >> "$BASH_ENV"
            # source "$BASH_ENV"
            # echo $PATH

            # curl -fLO https://go.dev/dl/go1.20.6.darwin-amd64.pkg
            # sudo installer -pkg go1.20.6.darwin-amd64.pkg -target /
            go version
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18.16.0
            node -v
      - run:
          name: Install Python
          command: |
            brew install python@3.10
            python3 -m venv venv
            source venv/bin/activate
            python --version
      - run:
          name: Build
          command: |
            cd PDF-Guru
            go install github.com/wailsapp/wails/v2/cmd/wails@latest
            go mod tidy
            cd frontend
            npm install
            cd ../thirdparty
            pip install pymupdf reportlab pillow loguru pyinstaller
            pyinstaller -F -w pdf.py
            cp dist/pdf* ../build/bin
            cd ..
            wails build
      - run:
          name: Save Artifacts
          command: |
            mkdir -p /tmp/artifacts
            cp build/bin/* /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts