name: deploy
run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  deploy-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: 安装 Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: 编译
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go mod tidy
          cd frontend
          npm install
          cd ../third_party
          pip install -r requirements.txt
          cd ..
          wails build

      - name: 部署Artifacts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release
          folder: build/bin